# Generated by Django 6.0.3 on 2026-03-18 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_pa_status_1e0453_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['receiver_city'], name='packages_pa_receive_b8e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tracking_number'], name='packages_pa_trackin_66fa4d_idx'),
        ),
    ]
