# Generated by Django 6.0.3 on 2026-03-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_packages_pa_status_1e0453_idx_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackinghistory',
            index=models.Index(fields=['timestamp'], name='tracking_tr_timesta_412c0b_idx'),
        ),
    ]
